### ISSUE TITLE
i dont like the new esp gui so much.

### ISSUE THREAD

**Issue by trashcan9292** [ic3w0lf22/Unnamed-ESP#18]
i want the rainbow mode button not change color with hard asf to change the color.
did u have this old guy tho?
![image](https://user-images.githubusercontent.com/96801285/180628008-87c24240-57c4-47e3-870f-7e1b60fe7c12.png)
i want it because it's comfortable for me

**Comment by ic3w0lf22** [comment]
https://github.com/ic3w0lf22/Unnamed-ESP/tree/03edb93f199b329b5940311e7c10627168406a21
