### ISSUE TITLE
its patched again.

### ISSUE THREAD

**Issue by ic3w0lf22** [ic3w0lf22/Unnamed-ESP#21]
its patched again.

_Originally posted by @bluescorpian in https://github.com/ic3w0lf22/Unnamed-ESP/issues/20#issuecomment-1297450272_

**Comment by ic3w0lf22** [comment]
made a new issue cuz we're spamming that guy's emails lol

**Comment by ic3w0lf22** [comment]
enable internal ui if its not already enabled, execute unnamed, press insert and let me know if any errors occured

**Comment by bluescorpian** [comment]
yeah, tested it. executing before it loaded causes it to lag, guess its not patched, just little bugged.

**Comment by ic3w0lf22** [comment]
this'll work just fine whatever [#20 ](https://github.com/ic3w0lf22/Unnamed-ESP/commit/d2c88c51169534fb85ca9f8935287d7e353fd1b7)
