### ISSUE TITLE
Phantom Forces patched

### ISSUE THREAD

**Issue by ripcrime** [ic3w0lf22/Unnamed-ESP#24]
Phantom forces is patched, only feature working is crosshair. Needs fix ASAP.

**Comment by ic3w0lf22** [comment]
can't fix without a dumb autoexec script/until synapse adds a feature to execute scripts under actor states or whatever the parallel lua shit is. you can try using [bbot's autoexec script](https://gist.githubusercontent.com/r-Lxd/c7ea24698533f3b505c1234c2e736a01/raw/82c762e2be418004a73c5c7403bd89daf2912cbd/pfnoactorshit.lua) to prevent pf running in parallel lua mode

**Comment by ripcrime** [comment]
figure something out bro come on, this isn't what I pay you to do

**Comment by ic3w0lf22** [comment]
pay first then

**Comment by ripcrime** [comment]
bro nah, give it to me like straight man to man, is it actually not fixable until synapse adds some shit? like be real.

**Comment by ripcrime** [comment]
this script is legit the best script for PF out of every single ESP script, and im sure a lot of other people would agree so if you could get this up and running again, fuck man it would be a miracle
