### ISSUE TITLE
Phantom Forces Patched, bbot autoexec no longer works

### ISSUE THREAD

**Issue by GoForIt01** [ic3w0lf22/Unnamed-ESP#25]
The bbot autoexec provided as a workaround no longer works, it causes the game to show some kind of screenshot with no gameplay available.

**Comment by ic3w0lf22** [comment]
they made a new script: https://cdn.discordapp.com/attachments/985030780734558248/1050488746790883358/raspy-detergent.lua

**Comment by GoForIt01** [comment]
Thanks, this currently works

**Comment by GoForIt01** [comment]
Nvm it's dead again, which dc server are these scripts coming from?

**Comment by sleaze5** [comment]
Try putting this in your autoexecute
```lua
loadstring(game:HttpGet("https://raw.githubusercontent.com/Spoorloos/scripts/main/pf-actor-bypass.lua"))()
```


v3rm thread: https://v3rmillion.net/showthread.php?tid=1195926

**Comment by GoForIt01** [comment]
@HunterAPI Thanks, works like a charm
